POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json

{
  "title": "Puede G2 competir en el msi y ganar?",
  "author": "Champi14",
  "url": "https://lapreviaBlogs.com",
  "userId": "661ce226949c01aef7e16554",
  "likes": 599
}