POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBlZHJpdG8xMjM0IiwiaWQiOiI2NjFkNDEzNDhkMTRkZTY2YTdjYjJmYjYiLCJpYXQiOjE3MTMxOTQxNTd9.Ov4Exc6vUQAfq3sUD6WM1GnYIXC0S9yo0qIRWQ4J8_M

{
  "title": "Soy un niño rata",
  "author": "Pedro the kido",
  "url": "https://ratkid.com",
  "likes": 1000000
}